FROM node:22-alpine

WORKDIR /app

# Corepack setup for native PNPM support
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable && corepack prepare pnpm@latest-10 --activate


COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY . .

RUN pnpm install --frozen-lockfile

# Copy rest of the application files

EXPOSE 3001

CMD ["pnpm", "run", "start:dev"]